name: main
"on": push
jobs:
  changes:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: read
      contents: read
    outputs:
      infra: ${{ steps.changed-files-yaml.outputs.infra_any_changed }}
    steps:
      - uses: actions/checkout@v5
      - uses: tj-actions/changed-files@v47
        id: changed-files-yaml
        with:
          files_yaml: |
            infra:
              - infra/**
  install-packages:
    runs-on: ubuntu-24.04
    needs:
      - changes
    steps:
      - uses: actions/checkout@v5
      - name: Install packages
        uses: ./.github/actions/install-packages
  test:
    runs-on: ubuntu-24.04
    needs:
      - install-packages
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 2
      - name: Install packages
        uses: ./.github/actions/install-packages
      - name: Run lefthook
        run: |
          eval "$(direnv export bash)"
          just test
  deploy-prd:
    if: ${{ needs.changes.outputs.infra == 'true' }}
    # yamllint disable-line rule:line-length
    uses: n4vysh/n4vysh.dev/.github/workflows/reusable-terragrunt-workflow.yml@main
    with:
      environment: production
      url: https://n4vysh.dev
      # yamllint disable-line rule:line-length
      role-to-assume: arn:aws:iam::804137327620:role/prd-website-github-actions
    needs:
      - changes
      - install-packages
      - test
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
  deploy-stg:
    if: ${{ needs.changes.outputs.infra == 'true' }}
    # yamllint disable-line rule:line-length
    uses: n4vysh/n4vysh.dev/.github/workflows/reusable-terragrunt-workflow.yml@main
    with:
      environment: staging
      url: https://stg.n4vysh.dev
      role-to-assume: dummy-arn
    needs:
      - changes
      - install-packages
      - test
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
