name: reusable terragrunt workflow
"on":
  workflow_call:
    inputs:
      environment:
        description: environment name
        required: true
        type: string
      url:
        description: environment URL
        required: true
        type: string
      role-to-assume:
        description: assume role ARN
        required: true
        type: string
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: true
        description: personal access token of GitHub
      INFRACOST_API_KEY:
        required: true
        description: infracost API key
jobs:
  set-target-dirs:
    runs-on: ubuntu-24.04
    outputs:
      dirs: ${{ steps.output-terragrunt-info.outputs.dirs }}
    steps:
      - uses: actions/checkout@v5
      - id: output-terragrunt-info
        run: .github/scripts/output-terragrunt-info.bash ${{inputs.environment}}
  plan:
    runs-on: ubuntu-24.04
    if: needs.set-target-dirs.outputs.dirs != '[]'
    needs:
      - set-target-dirs
    strategy:
      fail-fast: false
      matrix:
        # yamllint disable-line rule:line-length
        dir: ${{ fromJson(needs.set-target-dirs.outputs.dirs) }}
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.url }}
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v5
      - name: Install packages
        uses: ./.github/actions/install-packages
      - name: Configure AWS Credentials
        if: inputs.environment != 'staging'
        uses: ./.github/actions/configure-aws-credentials
        with:
          role-to-assume: ${{ inputs.role-to-assume }}
      - name: Run terragrunt plan
        env:
          ENV: ${{ inputs.environment }}
          DIR: ${{ matrix.dir }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
        run: |
          eval "$(direnv export bash)"
          just plan
        working-directory: ./infra/terragrunt/
  apply:
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/main'
    needs:
      - set-target-dirs
      - plan
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.url }}
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v5
      - name: Install packages
        uses: ./.github/actions/install-packages
      - name: Configure AWS Credentials
        if: inputs.environment != 'staging'
        uses: ./.github/actions/configure-aws-credentials
        with:
          role-to-assume: ${{ inputs.role-to-assume }}
      - name: Run terragrunt apply
        env:
          ENV: ${{ inputs.environment }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          eval "$(direnv export bash)"
          just apply
        working-directory: ./infra/terragrunt/
